model:
  params:
    cnn_channels: [32, 64]
    gru_hidden: 128
    gru_layers: 1
    use_cbam: true
    bidirectional: false # <--- 改为单向

    # === 变量 A ===
    sequence_order: row
    # === 变量 B ===
    attn_type: add
    dropout: 0.5

data:
  input_shape: [8, 8]
  train_path: CleanData/data/step6_normalized/train.csv
  val_path: CleanData/data/step6_normalized/val.csv
  test_path: CleanData/data/step6_normalized/test.csv
  label_col: label_int
  ignore_cols: [label]

training:
  run_root: results/ablation_study/uni_gru  # 结果单独存放
  batch_size: 256
  epochs: 100
  learning_rate: 1e-3
  early_stopping_patience: 10